name: swift_charts
description: Simple charts using package:web and canvas.
version: 1.2.0
homepage: https://github.com/coffee-software/swift_charts
environment:
  sdk: ^3.4.0
dependencies:
  web: ^1.1.1
dev_dependencies:
  test: any
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  lints: ^6.0.0
